import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { Readable } from 'stream';

export interface PdfSection {
  title: string;
  content: { label: string; value: string }[];
}

export function createBasePdf(): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    bufferPages: true,
  });
  return doc;
}

export function addHeader(doc: PDFKit.PDFDocument, title: string, docNumber: string, date: Date) {
  // Company header
  doc.fontSize(20).font('Helvetica-Bold').text('Tools Act', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('บริษัท ทูลส์ แอคท์ จำกัด', { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.5);

  // Document info
  doc.fontSize(14).font('Helvetica-Bold').text(title, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).font('Helvetica');
  doc.text(`Document No / เลขที่เอกสาร: ${docNumber}`, { align: 'right' });
  doc.text(`Date / วันที่: ${formatDateThai(date)}`, { align: 'right' });
  doc.moveDown(1);
}

export function addSection(doc: PDFKit.PDFDocument, section: PdfSection) {
  doc.fontSize(11).font('Helvetica-Bold').text(section.title);
  doc.moveDown(0.3);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke().strokeColor('#000000');
  doc.moveDown(0.3);

  for (const row of section.content) {
    const y = doc.y;
    doc.fontSize(9).font('Helvetica-Bold').text(row.label, 50, y, { width: 180 });
    doc.fontSize(9).font('Helvetica').text(row.value || '—', 240, y, { width: 305 });
    doc.moveDown(0.4);
  }
  doc.moveDown(0.5);
}

export function addSignatureField(doc: PDFKit.PDFDocument, label: string, x: number, y: number) {
  doc.fontSize(9).font('Helvetica').text(label, x, y);
  doc.moveTo(x, y + 30).lineTo(x + 180, y + 30).stroke();
  doc.fontSize(8).text('Signature / ลายเซ็น', x, y + 33);
  doc.moveTo(x, y + 60).lineTo(x + 180, y + 60).stroke();
  doc.fontSize(8).text('Date / วันที่', x, y + 63);
}

export function addFooter(doc: PDFKit.PDFDocument) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const bottom = doc.page.height - 40;
    doc.fontSize(8).font('Helvetica').fillColor('#666666');
    doc.text(
      `Page ${i - range.start + 1} of ${range.count} | Generated by Tools Act Rental System`,
      50,
      bottom,
      { align: 'center', width: 495 },
    );
    doc.fillColor('#000000');
  }
}

export async function savePdfToFile(
  doc: PDFKit.PDFDocument,
  filePath: string,
): Promise<void> {
  await fs.promises.mkdir(path.dirname(filePath), { recursive: true });
  return new Promise((resolve, reject) => {
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

function formatDateThai(date: Date): string {
  return date.toLocaleDateString('th-TH', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
